apiVersion: v1
kind: Service
metadata:
  name: zooclient-external-service
  labels:
    app: zooclient
spec:
  type: NodePort
  selector:
    app: zooclient
  ports:
    - name: inbound
      protocol: TCP
      port: 8085
      targetPort: 8085
      nodePort: 30111